# Generated by Django 3.0 on 2019-12-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_candidate_interviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
